# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

# https://www.jeremydaly.com/how-to-manage-serverless-environment-variables-per-stage/
# https://serverless-stack.com/chapters/stages-in-serverless-framework.html
# https://serverless.com/framework/docs/providers/aws/guide/variables/#referencing-cli-options

service: server

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
    name: aws
    runtime: nodejs12.x
    profile: byor
    # you can overwrite defaults here
    stage: ${opt:stage,'dev'}
    region: ${opt:region,'eu-west-1'}
    deploymentBucket:
        name: ${self:provider.stage}--byor-voting
    environment:
        MONGO_URI: ${ssm:${self:provider.stage}ByorMongoUri~true}
        MONGO_DB_NAME: ${ssm:${self:provider.stage}ByorMongoDbName}
        JWT_SECRET_KEY: ${ssm:${self:provider.stage}ByorJwtKey~true}
        MAILGUN_API_KEY: 'my-mailgun-key'
        MAILGUN_DOMAIN: 'my-domain'

functions:
    executeService:
        handler: handler.executeService
        events:
            - http:
                  path: executeService
                  method: post
                  cors: true
            - http:
                  path: executeService/votes/blips.csv
                  method: get
                  cors: true
            - http:
                  path: executeService/votes/{id}/blips.csv
                  method: get
                  request:
                      parameters:
                          paths:
                              id: true
                  cors: true
            - http:
                  path: executeService/votes/{id}/revote/blips.csv
                  method: get
                  request:
                      parameters:
                          paths:
                              id: true
                  cors: true

package:
    individually: true

custom:
    scripts:
        hooks:
            'after:deploy:finalize': >
                MONGO_URI=${self:provider.environment.MONGO_URI}
                MONGO_DB_NAME=${self:provider.environment.MONGO_DB_NAME}
                npm run migrate:ts:up

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-plugin-scripts
